name: deploy_to_gcloud
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "checkout code"
      - run: |
          echo "build"
  deploy_to_dev:
    runs-on: ubuntu-latest
    if: ${{ github.ref }} == 'refs/heads/dev'
    environment: dev
    steps:
      - run: |
          echo "deploying to dev"
  deploy_to_test:
    runs-on: ubuntu-latest
    if: ${{ github.ref }} == 'refs/heads/integrate'
    environment: test
    steps:
      - run: |
          echo "deploying to test"
  deploy_to_uat:
    runs-on: ubuntu-latest
    if: ${{ github.ref }} == 'refs/heads/release'
    environment: uat
    steps:
      - run: |
          echo "deploying to uat"
  deploy_to_prod:
    runs-on: ubuntu-latest
    if: ${{ github.ref }} == 'refs/heads/main'
    environment:
      name: prod
    steps:
      - run: |
          echo "deploy to cloud is running successfully"
      - run: |
          echo "something more to do"
  deploy_to_poc:
    runs-on: ubuntu-latest
    environment: poc
    steps:
      - run: |
          echo "deploying to poc"
