name: deploy_to_gcloud
on: [push]
jobs:
  build:
    steps:
      - run: |
          echo "checkout code"
      - run: |
          echo "build"
  deploy_to_gcloud:
    steps:
      - run: |
          echo "deploy to cloud is running successfully"
